import React from 'react';
import './ScrollingText.css';

const ScrollingText = () => {
  return (
    <div className="scrolling-container">
      <div className="scrolling-text">
        {/* Repeat the content in a way that they scroll seamlessly */}
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
        <p>EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI EVERYDAY CHICKEN AND MANDI </p>
      </div>
    </div>
  );
};

export default ScrollingText;
