name: Deploy to Hostinger

on:
  push:
    branches:
      - home  # Use your working branch name
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js and Build
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.rabeehraidan.com  # Your Hostinger FTP server
          username: ${{ secrets.FTP_USERNAME }}  # Securely fetch from GitHub Secrets
          password: ${{ secrets.FTP_PASSWORD }}  # Securely fetch from GitHub Secrets
          local-dir: dist/  # Your build output folder
          server-dir: /public_html/  # Change if needed


