name: Deploy to Hostinger

on:
  push:
    branches:
      - home  # Change this if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js and Build
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftp.yourdomain.com  # Replace with your Hostinger FTP server
          username: your-ftp-username # Replace with your Hostinger FTP username
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/  # Make sure this matches your build output folder
          server-dir: /public_html/  # Change if your website is in a subfolder
